name: SelfTest

on:
  push:
    branches: [ "main" ]

jobs:
  selfcheck:
    runs-on: self-hosted
    steps:
    - name: hi 1
      run: |
        cd D:\dev\workspace\demo
        git pull origin main
        net user
        set PATH=%PATH%;D:\dev\tool\jdk-21.0.3\bin
        java -version
        mvn clean install
  build:
    runs-on: ubuntu-latest
    steps:
    - name: hi 2
      run: echo hi 2
