name: SelfTest

on:
  push:
    branches: [ "main" ]

jobs:
  selfcheck:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: hi 1
      run: echo hi 1 ${{ github.workspace }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  build:
    runs-on: ubuntu-latest
    steps:
    - name: hi 2
      run: echo hi 2
