name: SelfTest

on:
  push:
    branches: [ "main" ]

jobs:
  selfcheck:
    runs-on: self-hosted
    steps:
    - name: hi 1
      run: echo hi 1
  build:
    runs-on: ubuntu-latest
    steps:
    - name: hi 2
      run: echo hi 2
