name: SelfTest

on:
  push:
    branches: [ "main" ]

jobs:
  selfcheck:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: hi 1
      run: |
        cd ${{ github.workspace }}
        git pull
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  build:
    runs-on: ubuntu-latest
    steps:
    - name: hi 2
      run: echo hi 2
